Feat/louis/permit2 router
mangrovedao/mangrove-strats pull request #13
Opened 2023-08-16 08:09 UTC by Louis-Amas

2023-09-18 19:14 UTC, espendk reviewed
Overall great! 

A few general questions/comments:
1. Permit2 is now a requirement, not an option. I.e, one cannot use `MangroveOrder` with direct ERC20 approvals. Are we sure we don't want to allow both?
   - If `MangroveOrder` is purely for our UI and we want to make Permit2 permissions a requirement in that, then it's fine.
   - But it seems there are some concerns in the community around the scams that Permit2 enable. So perhaps we should retain the option of normal approvals?
2. Would be great if we could validate this in the SDK and web app before the audit. Is that possible?


I also added some comments and questions on naming, comments, and style, but not sure if that's premature at this time? So stopped and will do a proper pass later.

2023-09-18 19:14 UTC, espendk commented on src/strategies/utils/StratTransferLib.sol
> +    );
why not call the function instead of using the low-level `call` ?

2023-09-18 19:14 UTC, espendk commented on src/strategies/utils/StratTransferLib.sol
> +    );
same as above

2023-09-21 11:46 UTC, Louis-Amas commented
> Overall great!
> 
> A few general questions/comments:
> 
>     1. Permit2 is now a requirement, not an option. I.e, one cannot use `MangroveOrder` with direct ERC20 approvals. Are we sure we don't want to allow both?
>        
>        * If `MangroveOrder` is purely for our UI and we want to make Permit2 permissions a requirement in that, then it's fine.
>        * But it seems there are some concerns in the community around the scams that Permit2 enable. So perhaps we should retain the option of normal approvals?
> 
>     2. Would be great if we could validate this in the SDK and web app before the audit. Is that possible?
> 
> 
> I also added some comments and questions on naming, comments, and style, but not sure if that's premature at this time? So stopped and will do a proper pass later.

1. This is true that it would make sense to have a non permit2 dependent MangroveOrder contract
2. Seems good for me :)

2023-09-21 12:35 UTC, Louis-Amas commented on src/strategies/utils/StratTransferLib.sol
> +    );
I want to check if the call reverted or not, and it's the way I'm used to doing it. Is there another option ?

2023-09-21 12:35 UTC, Louis-Amas commented on src/strategies/utils/StratTransferLib.sol
> +    );
same as above too :)

2023-09-21 12:38 UTC, Louis-Amas commented on src/strategies/utils/StratTransferLib.sol
> +///@title This library helps with safely interacting with ERC20 tokens
Done

2023-09-21 12:38 UTC, Louis-Amas commented on src/strategies/MangroveOrder.sol
> +  ///@param permit2 The permit2 contract
Done

2023-09-21 12:38 UTC, Louis-Amas commented on src/strategies/MangroveOrder.sol
> +  ///@notice pull inbound_tkn from the msg.sender with permit and then the forward market order to MGV
Done

2023-09-21 12:38 UTC, Louis-Amas commented on script/toy/MangroveJs.s.sol
> +    permit2 = IPermit2(deployPermit2.deployPermit2()); // deploy permit2 using the precompiled bytecode
Done

2023-09-21 12:39 UTC, Louis-Amas commented on script/strategies/mangroveOrder/deployers/PolygonMangroveOrderDeployer.s.sol
> +      permit2: IPermit2(envAddressOrName("Permit2", "Permit2")),
Done

2023-09-21 12:39 UTC, Louis-Amas commented on script/strategies/mangroveOrder/deployers/MumbaiMangroveOrderDeployer.s.sol
> +      permit2: IPermit2(envAddressOrName("Permit2", "Permit2")),
Done

2023-09-21 12:39 UTC, Louis-Amas commented on script/strategies/mangroveOrder/deployers/MangroveOrderDeployer.s.sol
> +      permit2: IPermit2(envAddressOrName("Permit2", "Permit2")),
Done

2023-09-22 12:31 UTC, espendk commented on src/strategies/utils/StratTransferLib.sol
> +    );
`try/catch` is the normal way to do it, I think?
https://docs.soliditylang.org/en/v0.8.21/control-structures.html#try-catch

2023-09-22 14:03 UTC, Louis-Amas commented on src/strategies/MangroveOrder.sol
> +  function marketOrderWithTransferApproval(
Here, I used market order as the function is a proxy for the Mangrove market order function. I think it's a not too bad, naming but I'm happy to discuss about better naming :)

2023-09-22 14:04 UTC, Louis-Amas commented on src/strategies/MangroveOrder.sol
> +    Forwarder(mgv, new Permit2Router(permit2), gasreq)
Not anymore, I created MangroveOrderWithPermit2 class that seperate two uses cases

2023-09-22 14:04 UTC, Louis-Amas commented on src/strategies/routers/AbstractRouter.sol
> +import {ISignatureTransfer} from "lib/permit2/src/interfaces/ISignatureTransfer.sol";
Removed

2023-09-22 14:08 UTC, Louis-Amas commented on src/strategies/routers/Permit2Router.sol
> +//@dev Maker contracts using this router must make sure that the reserve approves the permit2 for all asset that will be pulled (outbound tokens), and then the user needs either approve router inside
Done

2023-09-22 14:12 UTC, Louis-Amas commented on src/strategies/routers/SimpleRouterWithoutGasReq.sol
> +contract SimpleRouterWithoutGasReq is AbstractRouter {
I switch to use mono

2023-09-22 14:15 UTC, Louis-Amas commented on src/strategies/routers/Permit2Router.sol
> +  function __pull__(
True removed it

2023-09-22 14:19 UTC, Louis-Amas commented on src/strategies/utils/StratTransferLib.sol
> +///@notice ERC20 tokens returning bool instead of reverting are handled.
True, fixed.

2023-09-22 14:20 UTC, Louis-Amas commented on test/script/strategies/mangroveOrder/deployers/MangroveOrderDeployer.t.sol
> +    fork.set("Permit2", permit2);
To get the address we need to deploy it, am I missing something ?

2023-09-22 14:25 UTC, Louis-Amas commented on src/strategies/MangroveOrder.sol
> +  function take(TakerOrder calldata tko) external payable returns (TakerOrderResult memory) {
I don't think it make sense now, as I separated MangroveOrder and MangroveOrderWithPermit2 contract

2023-09-22 14:27 UTC, Louis-Amas commented on src/strategies/MangroveOrder.sol
> +  function __take__(TakerOrder calldata tko) internal returns (TakerOrderResult memory res) {
- I renamed it to __take, could you link me to a document where the special meaning is define ?
- Changed it, I don't know why but I tend to always define function before they are called.

2023-09-22 14:30 UTC, Louis-Amas commented on src/strategies/routers/Permit2Router.sol
> +  ///@return pulled The amount pulled if successful; otherwise, 0.
Fixed it

2023-09-22 14:38 UTC, Louis-Amas commented on src/strategies/utils/StratTransferLib.sol
> +    );
Nice :)
Didn't knew about it, maybe because I'm traumatized with language with exceptions ahah.

2023-09-22 14:38 UTC, Louis-Amas commented on src/strategies/utils/StratTransferLib.sol
> +    );
Fixed

2023-09-22 14:43 UTC, Louis-Amas commented on test/strategies/MgvOrder.t.sol
> +    // always unlimitted approval permit2
Fixed

2023-09-22 14:45 UTC, Louis-Amas commented on test/strategies/MgvOrder.t.sol
> +  function __freshTaker__(uint balBase, uint balQuote, address fresh_taker) internal {
Fixed.

2023-09-24 15:10 UTC, espendk commented on test/script/strategies/mangroveOrder/deployers/MangroveOrderDeployer.t.sol
> +    fork.set("Permit2", permit2);
The tests don't actually run any Permit2 code I believe, so could just use a fresh address.

2023-09-24 15:10 UTC, espendk commented on test/strategies/MgvOrder.t.sol
> +    permit2.approve(address(base), address(mgo.router()), type(uint160).max, type(uint48).max);
We should be consistent, so since the macro is used in the rest of the code base, new code should use it as well.

2023-09-24 16:45 UTC, espendk requested changes
lgtm, pending addressing comments.

@jkrivine and/or @lnist should also review this IMO.

2023-09-24 16:45 UTC, espendk commented on src/strategies/utils/Permit2TransferLib.sol
>  ///@notice ERC20 tokens returning bool instead of reverting are handled.
I don't see any handling of this in the code?

2023-09-24 16:45 UTC, espendk commented on src/strategies/MangroveOrderWithPermit2.sol
> +  ///@notice MangroveOrderWithPermit2 is a Forwarder logic with a simple router.
Uses a Permi2 router, not a simple router

2023-09-24 16:45 UTC, espendk commented on src/strategies/MangroveOrderWithPermit2.sol
> +contract MangroveOrderWithPermit2 is BaseMangroveOrder {
Comment like on the other MangroveOrder contracts, highlighting the difference (Permit2) and how it works.

2023-09-24 16:45 UTC, espendk commented on src/strategies/MangroveOrderWithPermit2.sol
> +  function marketOrderWithTransferApproval(
Perhaps there should be `*Permit` and `*Allowance` variants of this, to allow for more gas-efficient market orders when the router already has a Permit2 allowance

2023-09-24 16:45 UTC, espendk commented on src/strategies/BaseMangroveOrder.sol
> +  ///@notice BaseMangroveOrder is a Forwarder logic with a simple router.
Should be updated now that this takes an `AbstractRouter`. Are there any requirements on the router or its use by `BaseMangroveOrder` that one should be aware of?

2023-09-24 16:45 UTC, espendk commented on src/strategies/BaseMangroveOrder.sol
> +///@dev requiring no partial fill *and* a resting order is interpreted here as an instruction to revert if the resting order fails to be posted (e.g., if below density).
Should describe that this can be used with any(?) router.

2023-09-24 16:45 UTC, espendk commented on src/strategies/BaseMangroveOrder.sol
> +  function __take(TakerOrder calldata tko) internal returns (TakerOrderResult memory res) {
`__X` is not an existing name pattern. For hooks (virtual functions that sub-contracts can implement) we use `__X__`. But this does not seem to be a hook, but an internal function for with the same name as internal function; For that, we often use the pattern `XInternal`.

```suggestion
  function takeInternal(TakerOrder calldata tko) internal returns (TakerOrderResult memory res) {
```

2023-09-25 08:50 UTC, Louis-Amas commented on script/strategies/mangroveOrder/deployers/MangroveOrderWithPermit2Deployer.s.sol
> +    Remember to activate it using ActivateMangroveOrder
Nope, fixed it:)

2023-09-25 08:54 UTC, Louis-Amas commented on src/strategies/utils/Permit2TransferLib.sol
>  ///@notice ERC20 tokens returning bool instead of reverting are handled.
Hmm, you can see that I wrap in a try catch the call to transferFrom and in case of revert I return a boolean.

2023-09-25 09:02 UTC, espendk commented on src/strategies/utils/Permit2TransferLib.sol
>  ///@notice ERC20 tokens returning bool instead of reverting are handled.
But you ignore the return value of transferFrom. So what if transferFrom returns false you return true which seems weird?

2023-09-25 09:05 UTC, Louis-Amas commented on src/strategies/MangroveOrderWithPermit2.sol
> +  function marketOrderWithTransferApproval(
Agreed will implement something today :)

2023-09-25 10:15 UTC, Louis-Amas commented on src/strategies/MangroveOrderWithPermit2.sol
> +  function marketOrderWithTransferApproval(
Added 3 market orders functions.

2023-09-25 10:16 UTC, jkrivine commented on test/script/strategies/mangroveOrder/deployers/MangroveOrderDeployer.t.sol
> +    fork.set("Permit2", permit2);
This script is testing the deployer for `MangroveOrderDeployer`, I believe there is not reason to deploy Permit2 here indeed

2023-09-25 10:16 UTC, jkrivine commented on src/strategies/BaseMangroveOrder.sol
> +  function __take(TakerOrder calldata tko) internal returns (TakerOrderResult memory res) {
We also use in the strat lib _f() for an internal function that is expected to have a public wrapper.

2023-09-25 10:16 UTC, jkrivine commented on src/strategies/MangroveOrder.sol
> +  function marketOrderWithTransferApproval(
`MangroveOrder` contracts do not display pure `marketOrder`, you have access to them using `take` function. Is there any reason why you would want to extend the ABI?

2023-09-25 10:16 UTC, jkrivine commented on src/strategies/MangroveOrder.sol
> +  function __take__(TakerOrder calldata tko) internal returns (TakerOrderResult memory res) {
See here:
https://github.com/mangrovedao/mangrove-strats/blob/1db4bc64820e90a75207f29594de9fcb550a0ce2/src/strategies/MangroveOffer.sol#L11-L16

2023-09-25 10:19 UTC, Louis-Amas commented on addresses/context/maticmum.json
Yep, here is the address: https://docs.uniswap.org/contracts/v3/reference/deployments

2023-09-25 17:40 UTC, espendk commented on src/strategies/BaseMangroveOrder.sol
> +  function __take(TakerOrder calldata tko) internal returns (TakerOrderResult memory res) {
Right, an internal wrapper in a *subcontract* :-)

2023-10-02 08:53 UTC, lnist commented on src/strategies/MangroveOrder.sol
> +  ///@notice take implementation
Is there a reason not to push this documentation down to IOrderLogic?

2023-10-02 08:54 UTC, lnist commented on src/strategies/routers/SimpleRouter.sol
> +import {IERC20} from "mgv_src/MgvLib.sol";
```suggestion
import {IERC20} from "mgv_src/IERC20.sol";
```

2023-10-02 09:10 UTC, Louis-Amas commented on src/strategies/MangroveOrder.sol
> +  ///@notice take implementation
Fixed :)

2023-10-04 15:17 UTC, jkrivine commented
Closing since this branch is now merged onto `feat/advancedRouting`

2023-10-04 15:17 UTC, closed without merging