Add simple aave logic
mangrovedao/mangrove-strats pull request #135
Opened 2023-11-16 13:23 UTC by maxencerb

2023-11-17 09:31 UTC, jkrivine requested changes

2023-11-17 09:31 UTC, jkrivine commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +    uint amount = strict ? routingOrder.amount : balanceOf(routingOrder.token, m, routingOrder.fundOwner);
this should be `overlyingBalanceOf` otherwise call will return if `fundOwner` has 0 underlying but everything in overlying.

2023-11-17 09:31 UTC, jkrivine commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +    uint amount = strict ? routingOrder.amount : balanceOf(routingOrder.token, m, routingOrder.fundOwner);
Semantics of `strict` is:
transfer at most `amount` if `strict` and all the `token` you can otherwise. If you want to implement the "transfer underlying first" policy then if !strict you should transfer
1. the whole balance of tokens from `fundOwner`
2. the whole aave deposit of tokens (transfer the whole balance of aToken from fundOwner and then redeem)
If strict then:
1. amount_0 = min(amount, token.balanceOf(fundOwner))
2. amount_1 = redeem from aave min(amount-amount_0, 0)
3. transfer amount_0 + amount_1

Yes we need to make sure we want the "transfer underlying first" policy. Did we commit to doing this?

2023-11-17 09:31 UTC, jkrivine commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +    if (debtBalanceOf(routingOrder.token, m, routingOrder.fundOwner) > 0) {
`debtBalanceOf` is quite costly we need to make sure we also want the "repay first" policy.

2023-11-17 09:31 UTC, jkrivine commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +      require(reason == bytes32(0), "AaveLogic/SupplyFailed");
what about `require(reason == bytes32(0), string(abi.encodePacked(reason)))` so as not to loose Aave's message?

2023-11-17 09:31 UTC, jkrivine commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +    balance += balanceOf(routingOrder.token, m, routingOrder.fundOwner);
to be corrected if we do not implement the "underlying first" policy. Otherwise all good. Maybe just add a comment to say that balanceOfReserve might not be entirely available in case of a liquidity crisis on AAVE

2023-11-19 19:39 UTC, maxencerb commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +    uint amount = strict ? routingOrder.amount : balanceOf(routingOrder.token, m, routingOrder.fundOwner);
No I think we should stick to only overlying, especially in a simple strat like this. It was just an error from my side

2023-11-19 19:44 UTC, maxencerb commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +    if (debtBalanceOf(routingOrder.token, m, routingOrder.fundOwner) > 0) {
Indeed, for this simple strat, we should then keep only lending. Repay has a better for Aave APR though, to consider later.

2023-11-19 19:45 UTC, maxencerb commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +      require(reason == bytes32(0), "AaveLogic/SupplyFailed");
In this case the last param is `noRevert` so It will throw inside Aave

2023-11-19 19:46 UTC, maxencerb commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +    balance += balanceOf(routingOrder.token, m, routingOrder.fundOwner);
indeed

2023-11-20 11:39 UTC, jkrivine requested changes

2023-11-20 11:39 UTC, jkrivine commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +    uint redeemed = _redeem(routingOrder.token, amount, msg.sender);
There is an issue with the `_redeem` function of `AAveMemoizer` which does not catch revert as `_supply` for instance. For uniformity it would be great to have `_redeem` returning `bytes32` with a `noRevert` argument.
The reason is that when you do external calls inside offerLogic you want to have a strict control of reverts (which make your trade fail).

2023-11-20 11:39 UTC, jkrivine commented on src/strategies/routing_logic/SimpleAaveLogic.sol
> +    _supply(routingOrder.token, routingOrder.amount, routingOrder.fundOwner, false);
same here I would use the `noRevert` flag to true and let caller decide it wants to revert

2023-11-20 15:33 UTC, jkrivine approved these changes
OK modulo call to _redeem in __pull__ in SimpleAaveLogic should have `noRevert=false`

2023-11-20 15:37 UTC, merged