Feat/amplifier offers
mangrovedao/mangrove-strats pull request #139
Opened 2023-11-18 10:53 UTC by jkrivine

2023-11-20 16:28 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +      SmartRouter(address(vars.proxy)).setLogic(vars.routingOrder, args.outboundLogic);
Reduce gas cost a little bit by doing a check on address before writing to heap, calling and storing 0 in router (reduce cost by ~200 per loop and ~3000 if no sourcing strat at all)

2023-11-20 17:08 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +  mapping(uint bundleId => uint[2][] ticks_offerIds) private __ticks_offerIdsOfBundleId;
bundling in a uint[2] is the same as using a struct, and easier to understand.

Furthermore, we should keep bundle => inbound_tkns in the same mapping as the second one because of the storage layout of dynamic arrays.

With this storage layout, [we would need to write the arrays length twice instead of once 
](https://docs.soliditylang.org/en/v0.8.17/internals/layout_in_storage.html#mappings-and-dynamic-arrays
)

Doing something like this would save ~20k gas regardless of the number of token

```solidity
struct BundleSingleOfferInfo {
  uint tickSpacing;
  uint offerId;
  IERC20 inbound_tkn;
}

mapping(uint bundleId => BundleSingleOfferInfo[] bundle_offers_info) private __bundleOffersInfo;
```

This specific order on struct is great to keep the uints having a single storage slot and then we a a partial storage slot with the address.

2023-11-20 17:10 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +    uint[2][] ticks_offerIds;
Having an array of struct is the same here as above, same in gas but easier to understand

2023-11-20 17:12 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +    uint[4][] params; // params[0]: inVolume, params[1] = gasreq, params[2] = provision, params[3] = tick
fixed size array and struct have same layout storage in memory so make a struct for ease of use.

2023-11-20 17:17 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +    AbstractRouter[] inboundLogics;
maybe we could bundle all these arguments in a single struct as they are supposed to be the same size in array. 

Because these are calldata, values set to 0 will cost less + we will only set the length of the dynamic once according to abi specification reducing calldata size by 64 bytes.

2023-11-20 17:37 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +  event EndBundle();
Subject to change if we keep this.

1. keep it

If we keep this, this means that we think other offers could have been created during the same tx. So we would need to specify EndBundle with the bundleId ?

2. drop it

If we add no args, we assume we will only do this during our tx or even create multiple bundles in which case we will know when to stop because we will be emitting InitBundle again.

Dropping it is a ~375 gas cost less.

The only reason to add this would be having a tx creating a bundle and a standalone offer created. Is it a usecase.

2023-11-20 17:40 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +    IERC20[] memory inbound_tkns,
bundling these two within an array of struc as well and dropping the fixed size array

2023-11-20 17:49 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +      }
It's too bad here we will write expiry date in memory 3 times. Maybe we should have an expiry date for the whole bundle. As such, maybe not using the `ExpirableForwarder`. Indeed, we have a mapping from offer to bundle already, so we don't need to have expiry for each offer.

It would save ~20k gas per offer.

2023-11-20 17:50 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +          }
if we have an expiry on a per bundle basis, same as above, we would save ~20k gas per offer for updating

2023-11-20 17:56 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +    IERC20[] memory inbound_tkns = __inboundTknsOfBundleId[bundleId];
Bundling in struct

2023-11-21 07:33 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +  mapping(uint bundleId => uint[2][] ticks_offerIds) private __ticks_offerIdsOfBundleId;
Ha but the reason I am doing this is precisely because you cannot write an array of structs in currently solidity...

2023-11-21 07:41 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +  event EndBundle();
Yes precisely. What happens if a user creates a bundle and then a regular offer?

2023-11-21 07:42 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +  event EndBundle();
besides 375 gas is probably not important at that stage

2023-11-21 07:43 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +      }
Yes I was thinking of an expiry per bundle as well and possibly setting the outbound logic for the whole bundle as well. But is it worth the pain knowing that you pay the extra gas upfront only (when you create the bundle) but not duing the offer execution (which is sort of what matters)

2023-11-21 07:48 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +  mapping(uint bundleId => uint[2][] ticks_offerIds) private __ticks_offerIdsOfBundleId;
Hum but now it seems you can. So yes of course if it does I will revert to using structs here instead.

2023-11-21 08:25 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +  mapping(uint bundleId => uint[2][] ticks_offerIds) private __ticks_offerIdsOfBundleId;
This works, just we have to take a different approach as to how to write it to storage, because it does not support converting memory array of struct to storage array of struct. We have to push the members of the struct directly to storage. Here is a working PoC I've made on remix.

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.8.2 <0.9.0;

contract Test {

    struct TestStruct {
        uint amount;
        uint decimals;
        address token;
    }

    mapping(uint bundleId => TestStruct[] tokens) public tokensMapping;

    function setMappingValue() public {
        TestStruct[] storage tokens = tokensMapping[0];
        tokens.push(TestStruct({
            amount: 1 ether,
            decimals: 1 ether,
            token: address(0)
        }));
        tokens.push(TestStruct({
            amount: 12 ether,
            decimals: 1 ether,
            token: address(0)
        }));
    }

}
```

2023-11-21 08:29 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +      }
1. logic per bundle

No we should not do that because some logic could be specific to some tokens (e.g. no market on Aave for the selected token).

2. bundle expiry

For the example of having 3 inbounds, so 3 offers, it would save 40k upfront + 40k per modifying offer. I agree it's not optimizing taking the offer but it would not cost more for the taker. I will write a small PR, I don't think there is much modifications to make.

2023-11-21 16:44 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +      }
- If we set all logics to 0, are we sure the proxy is going to be created ?
- if we have no inbound logic, the vars.proxy is going to be set to address(0) once setting the outbound logic

Maybe we should put line 127 : 

```solidity
(vars.proxy,) = ROUTER_FACTORY.instantiate(msg.sender, ROUTER_IMPLEMENTATION);
```

before the loop. Plus, it will save some call to the router factory and insure the router proxy is created (or creates it) when creating a bundle

2023-11-21 17:03 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +            }
We can put a continue statement after retract offer, setting expiry after if we retract is not necessary. (I don't know if `continue` exists in solidity but at least an `else if`)

2023-11-21 17:06 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +      );
Only because I don't know the core protocol v2 very well, isn't there any market lock happening in here ? For example, if there was a `marketOrder` happening before creating new orders and this market order triggers one of the other market we want to enter ? Just like in the updateBundle function ?

2023-11-21 17:11 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +        freeWei += _retractOffer(olKey_i, bundle[i].offerId, deprovision);
Here we don't check if the market is locked ? I mean if called by the EAO no problem. But if called inside the `__get__` that is a problem no ?

2023-11-21 21:50 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +      );
The strat never creates newOffer during offer logic execution. So this public function is essentially called externally. So if it is called in a context where the offer list is locked, it is the expected behavior that the function should revert.

2023-11-21 21:52 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +        freeWei += _retractOffer(olKey_i, bundle[i].offerId, deprovision);
Same here. This is used in the context of an external call aiming at retracting the bundle not during the execution of an offerLogic.

2023-11-22 07:28 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +        freeWei += _retractOffer(olKey_i, bundle[i].offerId, deprovision);
yes it is on line 323

2023-11-22 18:06 UTC, maxencerb requested changes

2023-11-22 18:06 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +    _setExpiry(0, bundleId, date);
We have to make sure the indexer will be able to catch this. The indexer would have to query the state of the blockchain for every offer. I like the idea of using the same function for expiry.

But, maybe we can trigger all subsequent events meaning triggering the events inside the for loop, and then modifying the deadline bundlewise.

Something is also that if someone tries to set a longer deadline offerwise than bundlewise, it is going to prefer the bundlewise deadline. Is this what we want ?

2023-11-23 09:11 UTC, maxencerb approved these changes

2023-11-23 21:44 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +    _setExpiry(0, bundleId, date);
good point not sure about this.

2023-11-23 21:47 UTC, merged