fix ownerOf resulting in wrong owner
mangrovedao/mangrove-strats pull request #209
Opened 2024-01-18 15:33 UTC by maxencerb

2024-01-21 13:24 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +
Yes but the bundle only contains the inbound token so the remainder of the code is using the "manipulated" `outbound_tkn` resulting in updating the offer of the caller anyway.

2024-01-21 13:53 UTC, jkrivine requested changes

2024-01-21 13:53 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +
Yes but the bundle only contains the inbound token so the remainder of the code is using the "manipulated" `outbound_tkn` resulting in updating the offer of the caller anyway.
I think the proper attack scenario is slightly more complex here is one:
```
Alice: bundle [1] WBTC/DAI [id 1] and WBTC/USDT [id 1]
Bob: bundle [2] WETH/DAI [id 1] 
Carl: bundle [3] WETH/USDT [id 1]

Bob: updateBundle(bundleId:1, outbound:WETH)
check: ownerOf(id:1, inbound: DAI, outbound: WETH) == bob --> True
update(id:1, outbound: WETH, inbound: DAI) <- the offer of bob.
update(id:1, outbound: WETH, inbound: USDT) <- the offer of Carl!
```
Maybe after the patch it's not worth putting the whole scenario here

2024-01-21 13:53 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
> +    require(__bundleIdOfOfferId[olKeyHash][offerId] == bundleId, "MgvAmplifier/invalidBundleId");
to save a storage read (hot) we can also use a `bytes32` as key for the bundle map. You would build the key in the `newBundle` function by hashing the concatenation of the fresh bundle id and the outbound token. Something like:
```
///@notice maps a `bundleHash` to a set of bundled offers
  mapping(bytes32 bundleKey => BundledOffer[]) private __bundles;
  uint private __bundleId;
[..]
function newBundle(FixedBundleParams calldata fx, VariableBundleParams[] calldata vr)
    public
    payable
    returns (bytes32 freshBundleKey)
  {
    HeapVarsNewBundle memory vars;

    freshBundleKey = keccak256(abi.encode(fx.outbound_tkn, __bundleId++));
    
    emit InitBundle(freshBundleKey);
[...]
```

2024-01-21 13:53 UTC, jkrivine commented on src/strategies/offer_forwarder/abstract/Forwarder.sol
> +    }
Yes. Possible issue with the old code is when an offer logic calls `_retractOffer` on a locked offer list, the call will throw but the freeWei would still be positive. Note that this is not an issue with current strats that have no funds locally (so there would be nothing to withdraw). But this could be an issue with someone writing a strat on top of Forwarder

2024-01-29 09:33 UTC, maxencerb commented on src/strategies/MangroveAmplifier.sol
> +    require(__bundleIdOfOfferId[olKeyHash][offerId] == bundleId, "MgvAmplifier/invalidBundleId");
The problem is that we would have to know the bundle id passed to the bundle key in order to validate the outbound token, so either add to the return of newBundle and the `InitBundle` event the `bundleId` and `bundleKey`, to pass these arguments as well when updating the offer. That would make it quite unreadable.

2024-01-30 14:17 UTC, Louis-Amas commented on src/strategies/MangroveAmplifier.sol
> +    // * the mapping __bundleIdOfOfferId[olKeyHash][offerId] will either return 0 or a a bundle id different than 2.
typo there is two "a"

2024-01-30 14:21 UTC, Louis-Amas commented on src/strategies/offer_forwarder/RenegingForwarder.sol
> +
I didn't fully follow, but why aren't we calling ?
```
_setReneging
```

2024-01-30 14:46 UTC, maxencerb commented on src/strategies/offer_forwarder/RenegingForwarder.sol
> +
When we called it here, we removed the reneging volume before computing the residual values to repost an offer. But, this volume is used as a temp value as the max volume, so when computing residual values, we would have used higher values than the `cond.volume`. Thus, we moved the resetting inside the `_updateOffer` to make sure we don't overpromis.

2024-02-01 09:51 UTC, jkrivine commented on src/strategies/MangroveAmplifier.sol
>      } else {
This does not address issue 7.7: the call to `_retractBundle` below will be undone when `missing > 0`. We should test missing == 0 below and maybe add a retractBundle in `posthookFallback` if we want to retract the whole bundle if liquidity is missing.

2024-02-02 09:08 UTC, jkrivine submitted a review, later dismissed

2024-02-02 09:16 UTC, Louis-Amas approved these changes

2024-02-16 10:30 UTC, Louis-Amas approved these changes

2024-02-16 10:35 UTC, merged