Feat/kandel init new offer
mangrovedao/mangrove-strats pull request #44
Opened 2023-09-13 11:14 UTC by lnist

2023-09-13 18:38 UTC, jkrivine requested changes

2023-09-13 18:38 UTC, jkrivine commented on src/strategies/offer_maker/market_making/kandel/abstract/GeometricKandel.sol
> +  ///@notice publishes bids/asks for the distribution given by
incomplete comment

2023-09-13 18:38 UTC, jkrivine commented on src/strategies/offer_maker/market_making/kandel/abstract/GeometricKandel.sol
> +    this.populate{value: msg.value}(distribution, firstAskIndex, parameters, baseAmount, quoteAmount);
can't we make populate use distribution in memory rather than in calldata to avoid this? This is quite gas costly (external call rather than a jump). Especially that on L2 you want to call populate with the explicit distribution only internally

2023-09-15 07:11 UTC, lnist commented on src/strategies/offer_maker/market_making/kandel/abstract/GeometricKandel.sol
> +  ///@notice publishes bids/asks for the distribution given by
Added more.

2023-09-15 08:26 UTC, lnist commented on src/strategies/offer_maker/market_making/kandel/abstract/DirectWithBidsAndAsksDistribution.sol
> +    bool createDual;
make parameter

2023-09-21 09:15 UTC, jkrivine commented on src/strategies/offer_maker/market_making/kandel/abstract/DirectWithBidsAndAsksDistribution.sol
> +  function populateChunk(
Can we call this function `_populateChunk` or `populateChunkInternal` ? I don't like an internal function to seemingly override a public one.

2023-09-21 09:15 UTC, jkrivine commented on src/strategies/offer_maker/market_making/kandel/abstract/GeometricKandel.sol
> +  function createDistribution(
same remark about public/internal overriding an external function. This makes the code hard to read.

2023-09-21 09:15 UTC, jkrivine commented on src/strategies/offer_maker/market_making/kandel/abstract/GeometricKandel.sol
> +  function populateChunkFromOffset(
Nice!

2023-09-21 09:15 UTC, jkrivine commented on src/strategies/offer_maker/market_making/kandel/abstract/GeometricKandel.sol
> +  function populateChunkFromOffset(
This is the function we want to optimize for L2. So it should eventually accept packed calldata.
Low hanging fruit is that `from`, `to`, `firstAskIndex`, `bidGives`, `bidAsk` can definitely hold on a single `uint`

2023-09-21 10:23 UTC, lnist commented on src/strategies/offer_maker/market_making/kandel/abstract/CoreKandel.sol
> +    setGasprice(gasprice);
Hm, I think we have always done that in the strats so we kept the pattern. You are right that the initial populate will anyway contain pricepoints and spread, and thus it could also contain gasprice (right now I think the SDK sets it to what it was, but SDK could set it to a default value if 0)

I am ok with removing it, wdyt?

2023-09-21 10:25 UTC, lnist commented on src/strategies/offer_maker/market_making/kandel/abstract/CoreKandel.sol
> +    populateChunk(bidDistribution, askDistribution, params.gasreq, params.gasprice);
I've changed it to have a local parameters.
It will call with 0 gasreq and gasprice if not set. That is up to the user to initialize correctly. First with populate (to also set spread, pricepoints) then populateChunk

2023-09-21 10:26 UTC, lnist commented on src/strategies/offer_maker/market_making/kandel/abstract/CoreKandel.sol
> +  ///@notice This function is used publicly after `populate` to reinitialize some indices or if multiple transactions are needed to split initialization due to gas cost.
changed to externally.

2023-09-21 10:27 UTC, lnist commented on src/strategies/offer_maker/market_making/kandel/abstract/DirectWithBidsAndAsksDistribution.sol
> +  function populateChunk(
Renamed to populateChunkInternal

2023-09-21 10:28 UTC, lnist commented on src/strategies/offer_maker/market_making/kandel/abstract/GeometricKandel.sol
> +  function populateChunkFromOffset(
Alright, I'll do this in a separate commit, but yes I agree. But there are many things that could be packed I think

2023-09-21 10:53 UTC, merged

2023-09-21 11:30 UTC, lnist commented on src/strategies/offer_maker/market_making/kandel/abstract/GeometricKandel.sol
> +  function createDistribution(
Hm this is intentionally public so it can be called from SDK to make a calculation. So I don't know what to change. One createDistribution reads storage but saves on parameters, the other doesn't read storage but then requires all parameters.
The first is to calculate when parameters are already set correctly, the other is for when not set or changing parameters.