Feat/remove default gasreq
mangrovedao/mangrove-strats pull request #97
Opened 2023-10-18 12:52 UTC by jkrivine

In order to prepare future development of strats where gas cost for executing an offer depends on routing, we remove here default gasreq from strats.

Main changes of this PR are in commit 2c84273e8b7ebbbe which does the following:
* removes `offerGasreq()` from `MangroveOffer` class (and related functions)
* removes `routerGasreq()` from `AbstractRouter` class  (and related functions)
* Kandel strats have a default gasreq for offers stored in `params` which accounts for the totality of the gas requirement to execute an offer.
* MangroveOrder no longer has a default gasreq, and the gas requirement is now an arguement of `TakerOrder` struct. This is to anticipate next development of MangroveOffer which will have offer specific custom sourcing strategies (and therefore variable gascosts).

2023-10-18 14:47 UTC, maxencerb approved these changes

2023-10-18 14:47 UTC, maxencerb commented on src/strategies/routers/abstract/MultiRouter.sol
This abstraction is going to be deleted anyway for our implementation

2023-10-23 08:39 UTC, lnist requested changes

2023-10-23 08:39 UTC, lnist commented on script/strategies/kandel/deployers/PolygonKandelSeederDeployer.s.sol
> +      aaveKandelGasreq: 628_000,
FYI these are not "correct" in the sense they have to be measured to the chain we want to deploy to for the tokens we want to use with the optimization settings we deploy with.

2023-10-23 08:39 UTC, lnist commented on script/strategies/kandel/deployers/PolygonKandelSeederDeployer.s.sol
> +      aaveKandelGasreq: 628_000,
Also - should we remove these default gasreqs completely and let is be seeder input? MangroveOrder in SDK needs to know a sensible gasreq, so maybe Kandel should do the same? This would remove gasreq completely from deployment.

2023-10-23 08:39 UTC, lnist commented on src/strategies/MangroveOrder.sol
> +      gasreq: tko.restingOrderGasreq, // using default gasreq of the strat
comment is stale

2023-10-23 08:39 UTC, lnist commented on src/strategies/offer_maker/market_making/kandel/Kandel.sol
>    constructor(IMangrove mgv, OLKey memory olKeyBaseQuote, uint gasreq, address reserveId)
gasreq is still passed in but unused?

2023-10-23 08:39 UTC, lnist commented on src/strategies/routers/abstract/MultiRouter.sol
If MultiRouter is deleted then I suggest we also delete it from develop so auditors don't spend time on it (they should not as it is not part of the scope, but if we can delete it then it is super clear :) )

2023-10-23 08:39 UTC, lnist commented on src/strategies/offer_maker/market_making/kandel/AaveKandel.sol
> +  ///@param gasreq the gas required to execute an offer of this Kandel strat
Is the idea that the gasreq is coupled to the router, so therefore we set it here? That kinda makes sense, but we could also just require a call to setGasreq. I'm ok with this though.

2023-10-23 08:40 UTC, lnist commented on src/strategies/interfaces/IOrderLogic.sol
> +    uint restingOrderGasreq;
Add natspec

2023-10-23 08:41 UTC, lnist commented on src/strategies/interfaces/IOrderLogic.sol
> +    uint restingOrderGasreq;
Allowing the user to specify gasreq was removed during the earlier audit. See https://docs.mangrove.exchange/assets/files/ChainSecurity_Mangrove_Association_ADDMA_MangroveOrder_audit-7e289d0c705233f1d69d419d7689cab5.pdf section 6.1 and 6.2

I think the fix in https://github.com/mangrovedao/mangrove-core/pull/70/commits ("addressing 5.1") is part of the fix, but later we also did mangrovedao/mangrove-core#103 which removed the ability to set gasreq for MangroveOrder. @jkrivine : Why did we do that?

2023-10-23 08:41 UTC, lnist commented on src/strategies/routers/abstract/MonoRouter.sol
> -abstract contract MonoRouter is AbstractRouter {
We need to update AUDIT_TRAIL if this is to be included in the audit now (you are targeting develop?) - both regarding removal of gasreq stuff, and the AUDIT_TRAIL mentions MonoRouter but now it is gone :)

2023-10-25 09:23 UTC, jkrivine commented on script/strategies/kandel/deployers/PolygonKandelSeederDeployer.s.sol
> +      aaveKandelGasreq: 628_000,
OK it's more a debate of deployment procedure than code, but agreed.

2023-10-25 09:35 UTC, jkrivine commented on src/strategies/offer_maker/market_making/kandel/Kandel.sol
>    constructor(IMangrove mgv, OLKey memory olKeyBaseQuote, uint gasreq, address reserveId)
no it is, gasreq is set at the end of the constructor.

2023-10-25 09:54 UTC, jkrivine commented on src/strategies/interfaces/IOrderLogic.sol
> +    uint restingOrderGasreq;
Yes but we implemented a fix that allows us to modify gasreq in Forwarder so it's fine to do it here. The issue was that `_updateOffer` in forwarder strats needs to take gasreq into account to potentially free some wei for the owner in case the new gasreq is lower than the old one.

2023-10-25 10:56 UTC, lnist commented on src/strategies/interfaces/IOrderLogic.sol
> +    uint restingOrderGasreq;
Agree, so let's leave it at that.

2023-10-25 12:32 UTC, lnist approved these changes

2023-10-25 12:36 UTC, maxencerb approved these changes

2023-10-25 12:36 UTC, merged